In [9]:
#Câu 1
import numpy as np
from numpy import dot, arccos, degrees
from numpy.linalg import norm
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
#a
tong = A + B
tichso = 3*A - 2*B
#b
tichvohuong = dot(A,B)
gocgiua = arccos(tichvohuong / (norm(A) * norm(B)))
goc2vecto = round(degrees(gocgiua), 3)
#c
tichmatran = C.T @ C
print("Câu 1a:", tong, tichso)
print("Câu 1b: dot = ", tichvohuong, ", góc = ", goc2vecto, "độ")
print("Câu 1c:", tichmatran)

Câu 1a: [3 3 1 5] [  4 -11  13 -10]
Câu 1b: dot =  -8 , góc =  108.376 độ
Câu 1c: [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [6]:
#Câu 2
import numpy as np
from numpy.linalg import det, matrix_rank
M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
#a
tich = M * N
#b
det_M = det(M)
#c
rank_N = matrix_rank(N)
print("Câu 2a: ", tich)
print("Câu 2b: ", det_M)
print("Câu 2c: ", rank_N)

Câu 2a:  [[ 0  2  6  0]
 [16 25 36  7]
 [56 72 90 22]
 [ 0 13 14  0]]
Câu 2b:  6.66133814775094e-16
Câu 2c:  2


In [10]:
#câu 3
import numpy as np
from numpy.linalg import inv
P = np.array([[2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
T_vec = np.array([4, 7, 9, 5])
#a
try:
    P_inv = inv(P)
    invertible = True
except np.linalg.LinAlgError:
    P_inv = None
    invertible = False
#b
x_solution = P_inv @ T_vec if invertible else None
#c
ktra = P @ x_solution if x_solution is not None else None
print("Câu 3a: nghịch đảo tồn tại =", invertible)
print("Câu 3b: nghiệm =", x_solution)
print("Câu 3c: kiểm tra =", ktra)

Câu 3a: nghịch đảo tồn tại = True
Câu 3b: nghiệm = [0.46511628 2.10465116 1.65116279 0.96511628]
Câu 3c: kiểm tra = [4. 7. 9. 5.]


In [11]:
#Câu 4
import numpy as np
from numpy.linalg import norm

Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])
#a,b
gtri, gtririeng = np.linalg.eig(Q)
#c
vectorieng = np.array([vec / norm(vec) for vec in gtririeng.T])

print("Câu 4a: giá trị riêng =", gtri)
print("Câu 4b: vector riêng =\n", gtririeng)
print("Câu 4c: vector riêng chuẩn hóa =\n", vectorieng)

Câu 4a: giá trị riêng = [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
Câu 4b: vector riêng =
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]
Câu 4c: vector riêng chuẩn hóa =
 [[ 0.83327121+0.j          0.455468  +0.j          0.31338154+0.j        ]
 [-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
 [-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]]


In [12]:
#Câu 5
import numpy as np
from numpy.linalg import inv, det

R = np.array([[1, -2, 3], [2, 0, 1], [-1, 1, 4]])
V = np.array([10, 8, 7])

x5 = np.linalg.solve(R, V)
R_inv = inv(R) if det(R) != 0 else None
x5_by_inv = R_inv @ V if R_inv is not None else None
frobenius_norm = np.linalg.norm(R, ord='fro')

print("Câu 5a: nghiệm =", x5)
print("Câu 5b: nghiệm qua nghịch đảo =", x5_by_inv)
print("Câu 5c: Frobenius norm =", frobenius_norm)


Câu 5a: nghiệm = [2.7826087  0.04347826 2.43478261]
Câu 5b: nghiệm qua nghịch đảo = [2.7826087  0.04347826 2.43478261]
Câu 5c: Frobenius norm = 6.082762530298219
