In [15]:
#Bài 1
import numpy as np
from numpy import linalg as LA
from math import acos, degrees
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
#a.Tổng A + B và tích số 2A + 3B
tongAB = A + B
tichso = 2 * A + 3 * B
print("Câu 1a: A + B =", tongAB)
print("2A + 3B =", tichso)
#b.Tích vô hướng và góc giữa hai vector
tichvohuong= np.dot(A, B)
norm_A = LA.norm(A)
norm_B = LA.norm(B)
cos_theta = tichvohuong / (norm_A * norm_B)
gocdo = round(degrees(acos(cos_theta)), 3)
print("Câu 1b: Tích vô hướng A * B =", tichvohuong)
print("Góc giữa hai vector A và B (độ) ≈", gocdo)
#c.Tích ma trận C × C^T
C = np.array([[2, -1, 3], [1, 4, -2], [0, 2, 5]])
tichCCt = C @ C.T
print("Câu 1c: C × Cᵗ =", tichCCt)

Câu 1a: A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]
Câu 1b: Tích vô hướng A * B = -5
Góc giữa hai vector A và B (độ) ≈ 99.594
Câu 1c: C × Cᵗ = [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [16]:
#Bài 2
import numpy as np
from numpy import linalg as LA
M = np.array([[2, -1, 3, 0], [1, 4, -2, 5], [0, 2, 6, -3], [-1, 0, 1, 4]])
N = np.array([[1, 3, -2, 0], [4, -1, 5, 2], [0, 2, 3, -1], [-3, 1, 0, 4]])
#a.Tích M×N
print("Câu 2a: M × N =", M @ N)
#b.Định thức M
print("Câu 2b: det(M) =", LA.det(M))
#c.Hạng của N
print("Câu 2c: rank(N) =", LA.matrix_rank(N))


Câu 2a: M × N = [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Câu 2b: det(M) = 409.00000000000017
Câu 2c: rank(N) = 4


In [17]:
#Bài 3
import numpy as np
from numpy import linalg as LA
P = np.array([[3, -1, 0, 2], [1, 4, -2, 0], [0, 1, 5, -1], [2, 0, 1, 3]])
b = np.array([6, 8, 3, 7])
#a.Tìm ma trận nghịch đảo của P
try:
    P_inv = LA.inv(P)
    print("Câu 3a Ma trận nghịch đảo của P:")
    print(np.round(P_inv, 4))
except LA.LinAlgError:
    print("Ma trận P không khả nghịch.")
    P_inv = None
#b.Giải hệ phương trình P·x = b
if P_inv is not None:
    x = P_inv @ b
    print("Câu 3b Nghiệm x của hệ phương trình P·x = b là:")
    print(np.round(x, 4))
else:
    print("Không thể giải hệ phương trình vì P không khả nghịch.")
    x = None
#c.Kiểm tra lại nghiệm
if x is not None:
    check = P @ x
    print("Câu 3c Kiểm tra: P·x =")
    print(np.round(check, 4))
    print("→ So sánh với b =", b)
else:
    print("Không kiểm tra được nghiệm.")

Câu 3a Ma trận nghịch đảo của P:
[[ 0.5     0.1     0.1    -0.3   ]
 [-0.1429  0.2     0.0571  0.1143]
 [-0.0357 -0.05    0.1643  0.0786]
 [-0.3214 -0.05   -0.1214  0.5071]]
Câu 3b Nghiệm x của hệ phương trình P·x = b là:
[2.     1.7143 0.4286 0.8571]
Câu 3c Kiểm tra: P·x =
[6. 8. 3. 7.]
→ So sánh với b = [6 8 3 7]


In [23]:
#Bài 4
Q = np.array([[5, -2, 1], [0, 3, -1], [2, 0, 4]])
#a.Giá trị riêng
eigvals, eigvecs = LA.eig(Q)
print("Câu 4a: Giá trị riêng =", np.round(eigvals, 4))
#b.Vector riêng
print("Câu 4b: Vector riêng =", np.round(eigvecs, 4))
#c.Chuẩn hóa vector riêng
normed_vecs = np.array([v / LA.norm(v) for v in eigvecs.T]).T
print("Câu 4c: Vector riêng đã chuẩn hóa =", np.round(normed_vecs, 4))


Câu 4a: Giá trị riêng = [6.3553+0.j     2.8223+1.0773j 2.8223-1.0773j]
Câu 4b: Vector riêng = [[ 0.7485+0.j     -0.3742+0.3423j -0.3742-0.3423j]
 [-0.1894+0.j      0.0947+0.5743j  0.0947-0.5743j]
 [ 0.6356+0.j      0.6356+0.j      0.6356-0.j    ]]
Câu 4c: Vector riêng đã chuẩn hóa = [[ 0.7485+0.j     -0.3742+0.3423j -0.3742-0.3423j]
 [-0.1894+0.j      0.0947+0.5743j  0.0947-0.5743j]
 [ 0.6356+0.j      0.6356+0.j      0.6356-0.j    ]]


In [24]:
#Bài 5
R = np.array([[4, -1, 2], [1, 3, -2], [0, 2, 5]])
b = np.array([12, 5, 9])
#a.Giải hệ Rx = b
x = LA.solve(R, b)
print("Câu 5a: Nghiệm x =", np.round(x, 4))
#b.Kiểm tra nghịch đảo và giải lại
if np.isclose(LA.det(R), 0):
    print("Ma trận R không khả nghịch")
else:
    R_inv = LA.inv(R)
    x2 = R_inv @ b
    print("Câu 5b: Nghịch đảo R =", np.round(R_inv, 4))
    print("Giải lại: x = ", np.round(x2, 4))
#c.Chuẩn Frobenius
fro_norm = LA.norm(R, ord='fro')
print("Câu 5c: Chuẩn Frobenius của R =", round(fro_norm, 4))

Câu 5a: Nghiệm x = [2.7882 1.5294 1.1882]
Câu 5b: Nghịch đảo R = [[ 0.2235  0.1059 -0.0471]
 [-0.0588  0.2353  0.1176]
 [ 0.0235 -0.0941  0.1529]]
Giải lại: x =  [2.7882 1.5294 1.1882]
Câu 5c: Chuẩn Frobenius của R = 8.0
