In [ ]:
#Bài 1
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print(tich)
np.dot(a,b)

32


np.int64(32)

In [ ]:
#Bài 2
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a,2)

a = np.array([1,2,-3])
np.linalg.norm(a,1)

np.float64(6.0)

In [ ]:
#Bài 3
def chuan(v,k):
  tong = 0
  for i in range(len(v)):
      tong = tong + abs(v[i]**k)
  ketqua = math.pow(tong, 1.0/k)
  return ketqua

import math
import numpy as np

a = np.array([1,2,-3])
print(chuan(a,1))
print(np.linalg.norm(a,1))
print(chuan(a,2))
print(np.linalg.norm(a,2))
print(chuan(a,3))
print(np.linalg.norm(a,3))
print(chuan(a,1000))
print(np.linalg.norm(a,1000))

6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
1.0442214818467515
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [ ]:
#Bài 4
from scipy import linalg
print(linalg.norm(a))
print(np.linalg.norm(a,100))
print(np.linalg.norm(a,1000))

3.7416573867739413
3.0
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [ ]:
#Bài 5
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([v1,v2,v3,v4])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)
v=(1.0/m)*MT.dot(mi)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[[13.8 -6.8 -4.3]
 [-6.8  9.8  3.3]
 [-4.3  3.3  5. ]]


In [ ]:
#Bài 6
import sympy as sym
x,y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1,-68],[1,1]])
v = sym.Matrix([0,1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [ ]:
#Bài 7
import sympy
x,y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A),0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print(sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


In [ ]:
#Bài 8
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)
A.dot(P)
P.dot(D)