In [ ]:
#Bài 1
import numpy as np
D = np.array([[1, 2], [3, 4]])
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)

[[1 2]
 [3 4]]


In [ ]:
#Bài 2
import numpy as np
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [ ]:
#Bài 3
import numpy as np
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Bài 4
from numpy import matlib
G = matlib.identity(5)
print("G =")
print(G)

H = matlib.randn(3, 2)
print("\nH =")
print(H)

K = matlib.zeros([4, 4])
print("\nK =")
print(K)


G =
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

H =
[[-1.21761023  0.6820826 ]
 [ 1.21068825  0.83709636]
 [ 0.75692768 -0.16326012]]

K =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Bài 5
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

M = np.asmatrix([[1, 2], [3, 4]])

for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]

    if i == 0:
        M = ci
    else:
        M = M.dot(ci)

print(M)

# Tính và in kết quả phân số
print(M[0, 0] / M[1, 0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936
